FROM ubuntu:24.10

RUN apt update && apt -y install software-properties-common curl python3 python3-venv \
    && rm -rf /var/lib/apt/lists/* \
    && echo 'Package: *\nPin: release o=LP-PPA-mozillateam\nPin-Priority: 1001\n' |  tee /etc/apt/preferences.d/mozilla-firefox \
    && add-apt-repository -y ppa:mozillateam/ppa \
    && apt -y  install firefox \
    && groupadd -g 1001 hventure \
    && useradd -rm -d /home/hventure -s /bin/bash -g hventure -G sudo -u 1001 hventure \
    && mkdir /home/hventure/application /home/hventure/.aws && chown -Rv 1001:1001 /home/hventure/ && chmod 700 /home/hventure/.aws && ln -s /bin/python3 /bin/python
USER hventure
RUN curl -sSL https://install.python-poetry.org | python3 -
COPY --chown=1001:1001 *.py *.toml /home/hventure/application/
RUN cd /home/hventure/application/ \
    && python -m venv venv \
    &&  . venv/bin/activate \
    && $HOME/.local/bin/poetry install \
    && deactivate
USER root
RUN apt -y remove curl software-properties-common && apt -y autoremove
USER hventure
WORKDIR /home/hventure/application
ENTRYPOINT ["/bin/bash"]

